[tasks.prepare]
depends = ["prepare-pdfs"]
description = "Prepare resources."

[tasks.cleanup]
hide = true
run = "rm -f architecture*.aux architecture*.log architecture*.toc architecture*.fdb* architecture*.fls"

[tasks.compile]
depends = ["prepare"]
description = "Compile architecture document into architecture.pdf"
run = "xelatex -interaction=nonstopmode architecture.tex"

[tasks.compile-en]
depends = ['prepare']
description = 'Compile English version of the architecture into architecture-en.pdf'
run = 'xelatex -interaction=nonstopmode architecture-en.tex'
