#!/bin/sh

export PUPPETEER_EXECUTABLE_PATH="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
find ./resources -name '*.mmd' | while read X; do
  echo "Compile $X into ${X%.mmd}.svg"
  mmdc -i "$X" -o "${X%.mmd}.svg" -b transparent
done
